# Generated by Django 5.2.5 on 2025-10-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address2_alter_customer_address3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
