# Generated by Django 5.2.5 on 2025-08-30 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Order_Finished', 'Order Finished'), ('Preparing', 'Preparing'), ('Order_Ready', 'Order Ready'), ('Order_Delivering', 'Oreder Delivering'), ('Order_Delivered', 'Order Delivered')], default='Order_Finished', max_length=50)),
                ('sub_total', models.FloatField()),
                ('discount_total', models.FloatField(null=True)),
                ('tax_total', models.FloatField()),
                ('shipping_price', models.FloatField()),
                ('grand_price', models.FloatField()),
                ('address', models.CharField(max_length=300)),
                ('payment_status', models.CharField(choices=[('Cash', 'Cash'), ('Visa', 'Visa'), ('Smart_Wallet', 'Smart Wallet')], max_length=50)),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('prduct', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product')),
            ],
        ),
    ]
