# Generated by Django 5.2.5 on 2025-08-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
