# Generated by Django 5.2.5 on 2025-08-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_discount_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='prduct',
            new_name='product',
        ),
    ]
